config/routes.rb
LanguageHover::Application.routes.draw do

  root 'notes#show'
  resource :notes, only: %i[show edit update], path: ""

end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  field :text, default: ""
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end

  def edit
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action do
    @note = Note.first
  end
  def show
  end

  def edit
  end

  def update
    @note.update_attributes update_params
    redirect_to root_path
  end

  protected
  def update_params
    params.require(:note).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LanguageHover</title>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0, user-scalable=no" %>
  <script type="text/javascript" src="//use.typekit.net/vkv6xet.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= stylesheet_link_tag "//cdnjs.cloudflare.com/ajax/libs/normalize/2.1.3/normalize.min.css" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="main_grid">
  <%= yield %>
</div>

</body>
</html>

app/views/notes/edit.html.erb
<%= form_for @note, url: notes_path do |f| %>
    <%= f.text_area :text %>
    <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<%= link_to "Edit", edit_notes_path, class: "edit" %>

<%= @note.to_html %>